### ISSUE TITLE
[Bug]: CSS affects spacing of non-Commander items

### ISSUE THREAD

**Issue by pjeby** [jsmorabito/obsidian-commander#90]
### Describe the bug

Commander's CSS sets `margin-right` for most `status-bar-item` and `titlebar-button` elements, but this affects buttons and status bar items that were not added by Commander, and whose spacing is negatively impacted.  For example, on Windows, the minimize, maximize and close buttons (in hidden frame mode) have their spacing changed, which throws a number of things off.

### Steps to reproduce

Set the button spacing to a very high or low number, and observe effects on:

- The spacing of the window controls (on Windows and Linux)
- The Quick Explorer status bar (items are spaced too wide or too narrow)
- In Pane Relief's Sliding Panes mode, the right sidebar toggle button ends up too far left or right, depending on spacing (it's positioned based on `--frame-right-space`, whose value is incorrect due to the change in spacing of the window controls)

### Expected Behavior

Changing the button spacing in Commander should not affect the window controls or anything else but Commander's own buttons.

### Additional context

I would suggest removing the `.titlebar-button` rule (since as far as I can tell, it is not actually used by Commander), and changing the `.status-bar-item` rule to only apply to `.cmdr` elements.  That is, replace this:

```scss
.titlebar-button:not(:last-child),
.status-bar-item:not(:last-child) {
	margin-right: calc(var(--cmdr-spacing) - 8px);
}
```

With this:

```scss
.cmdr.status-bar-item:not(:last-child) {
	margin-right: calc(var(--cmdr-spacing) - 8px);
}
```

This should keep the CSS interference to a minimum.

### Operating system

Windows
